apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-back
  labels:
    app: my-back-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-back-app
  template:
    metadata:
      labels:
        app: my-back-app
    spec:
      containers:
        - name: node-back
          image: demorbe.azurecr.io/backdemo:latest
          ports:
            - name: web
              containerPort: 80
              protocol: TCP