apiVersion: v1
kind: Pod
metadata:
  name: mi-pod
  labels:
    role: mi-etiqueta
spec:
  containers:
    - name: hello
      image: hello-node
      imagePullPolicy: Never
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP